sudo: required
services:
  - docker

before_install:
  - docker build -t server/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true server/docker-react npm run test -- --coverage

language: generic 
